# Generated by Django 5.2.11 on 2026-04-20 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exams/')),
                ('classification', models.CharField(choices=[('benign', 'Benigno'), ('malignant', 'Maligno'), ('normal', 'Normal')], max_length=20)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.institution')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.patient')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='core.profile')),
            ],
        ),
    ]
