# Generated by Django 5.2.11 on 2026-04-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exam_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='classification',
            field=models.CharField(blank=True, choices=[('benign', 'Benigno'), ('malignant', 'Maligno'), ('normal', 'Normal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
